name: keepalive

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

concurrency:
  group: keepalive
  cancel-in-progress: false

permissions:
  actions: write

jobs:
  keepalive:
    name: Keep Workflows Alive on Ubuntu 24.04
    runs-on: ubuntu-24.04
    steps:
      - name: Re-enable Workflows
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh workflow enable keepalive.yml --repo $GITHUB_REPOSITORY
          gh workflow enable test.yml --repo $GITHUB_REPOSITORY
